<?php

/**
 * start source :   https://www.science.co.il/language/Locale-codes.php
 * see also :       https://msdn.microsoft.com/en-us/library/ms912047(v=winembedded.10).aspx
 */

return [
    [
        'name'     => 'Afrikaans',
        'language' => 'af',
        'locale'   => 'af',
        'lcid'     => 1078,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Albanian',
        'language' => 'sq',
        'locale'   => 'sq',
        'lcid'     => 1052,
        'codepage' => 1250,
    ],
    [
        'name'     => 'Amharic',
        'language' => 'am',
        'locale'   => 'am',
        'lcid'     => 1118,
    ],
    [
        'name'     => 'Arabic - Algeria',
        'language' => 'ar',
        'locale'   => 'ar_DZ',
        'lcid'     => 5121,
        'codepage' => 1256,
    ],
    [
        'name'     => 'Arabic - Bahrain',
        'language' => 'ar',
        'locale'   => 'ar_BH',
        'lcid'     => 15361,
        'codepage' => 1256,
    ],
    [
        'name'     => 'Arabic - Egypt',
        'language' => 'ar',
        'locale'   => 'ar_EG',
        'lcid'     => 3073,
        'codepage' => 1256,
    ],
    [
        'name'     => 'Arabic - Iraq',
        'language' => 'ar',
        'locale'   => 'ar_IQ',
        'lcid'     => 2049,
        'codepage' => 1256,
    ],
    [
        'name'     => 'Arabic - Jordan',
        'language' => 'ar',
        'locale'   => 'ar_JO',
        'lcid'     => 11265,
        'codepage' => 1256,
    ],
    [
        'name'     => 'Arabic - Kuwait',
        'language' => 'ar',
        'locale'   => 'ar_KW',
        'lcid'     => 13313,
        'codepage' => 1256,
    ],
    [
        'name'     => 'Arabic - Lebanon',
        'language' => 'ar',
        'locale'   => 'ar_LB',
        'lcid'     => 12289,
        'codepage' => 1256,
    ],
    [
        'name'     => 'Arabic - Libya',
        'language' => 'ar',
        'locale'   => 'ar_LY',
        'lcid'     => 4097,
        'codepage' => 1256,
    ],
    [
        'name'     => 'Arabic - Morocco',
        'language' => 'ar',
        'locale'   => 'ar_MA',
        'lcid'     => 6145,
        'codepage' => 1256,
    ],
    [
        'name'     => 'Arabic - Oman',
        'language' => 'ar',
        'locale'   => 'ar_OM',
        'lcid'     => 8193,
        'codepage' => 1256,
    ],
    [
        'name'     => 'Arabic - Qatar',
        'language' => 'ar',
        'locale'   => 'ar_QA',
        'lcid'     => 16385,
        'codepage' => 1256,
    ],
    [
        'name'     => 'Arabic - Saudi Arabia',
        'language' => 'ar',
        'locale'   => 'ar_SA',
        'lcid'     => 1025,
        'codepage' => 1256,
    ],
    [
        'name'     => 'Arabic - Syria',
        'language' => 'ar',
        'locale'   => 'ar_SY',
        'lcid'     => 10241,
        'codepage' => 1256,
    ],
    [
        'name'     => 'Arabic - Tunisia',
        'language' => 'ar',
        'locale'   => 'ar_TN',
        'lcid'     => 7169,
        'codepage' => 1256,
    ],
    [
        'name'     => 'Arabic - United Arab Emirates',
        'language' => 'ar',
        'locale'   => 'ar_AE',
        'lcid'     => 14337,
        'codepage' => 1256,
    ],
    [
        'name'     => 'Arabic - Yemen',
        'language' => 'ar',
        'locale'   => 'ar_YE',
        'lcid'     => 9217,
        'codepage' => 1256,
    ],
    [
        'name'     => 'Armenian',
        'language' => 'hy',
        'locale'   => 'hy',
        'lcid'     => 1067,
    ],
    [
        'name'     => 'Assamese',
        'language' => 'as',
        'locale'   => 'as',
        'lcid'     => 1101,
    ],
    [
        'name'     => 'Azeri - Cyrillic',
        'language' => 'az',
        'locale'   => 'az_AZ',
        'lcid'     => 2092,
        'codepage' => 1251,
    ],
    [
        'name'     => 'Azeri - Latin',
        'language' => 'az',
        'locale'   => 'az_AZ',
        'lcid'     => 1068,
        'codepage' => 1254,
    ],
    [
        'name'     => 'Basque',
        'language' => 'eu',
        'locale'   => 'eu',
        'lcid'     => 1069,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Belarusian',
        'language' => 'be',
        'locale'   => 'be',
        'lcid'     => 1059,
        'codepage' => 1251,
    ],
    [
        'name'     => 'Bengali - Bangladesh',
        'language' => 'bn',
        'locale'   => 'bn',
        'lcid'     => 2117,
    ],
    [
        'name'     => 'Bengali - India',
        'language' => 'bn',
        'locale'   => 'bn',
        'lcid'     => 1093,
    ],
    [
        'name'     => 'Bosnian',
        'language' => 'bs',
        'locale'   => 'bs',
        'lcid'     => 5146,
    ],
    [
        'name'     => 'Bulgarian',
        'language' => 'bg',
        'locale'   => 'bg',
        'lcid'     => 1026,
        'codepage' => 1251,
    ],
    [
        'name'     => 'Burmese',
        'language' => 'my',
        'locale'   => 'my',
        'lcid'     => 1109,
    ],
    [
        'name'     => 'Catalan',
        'language' => 'ca',
        'locale'   => 'ca',
        'lcid'     => 1027,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Chinese - China',
        'language' => 'zh',
        'locale'   => 'zh_CN',
        'lcid'     => 2052,
    ],
    [
        'name'     => 'Chinese - Hong Kong SAR',
        'language' => 'zh',
        'locale'   => 'zh_HK',
        'lcid'     => 3076,
    ],
    [
        'name'     => 'Chinese - Macau SAR',
        'language' => 'zh',
        'locale'   => 'zh_MO',
        'lcid'     => 5124,
    ],
    [
        'name'     => 'Chinese - Singapore',
        'language' => 'zh',
        'locale'   => 'zh_SG',
        'lcid'     => 4100,
    ],
    [
        'name'     => 'Chinese - Taiwan',
        'language' => 'zh',
        'locale'   => 'zh_TW',
        'lcid'     => 1028,
    ],
    [
        'name'     => 'Croatian',
        'language' => 'hr',
        'locale'   => 'hr',
        'lcid'     => 1050,
        'codepage' => 1250,
    ],
    [
        'name'     => 'Czech',
        'language' => 'cs',
        'locale'   => 'cs',
        'lcid'     => 1029,
        'codepage' => 1250,
    ],
    [
        'name'     => 'Danish',
        'language' => 'da',
        'locale'   => 'da',
        'lcid'     => 1030,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Dutch - Belgium',
        'language' => 'nl',
        'locale'   => 'nl_BE',
        'lcid'     => 2067,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Dutch - Netherlands',
        'language' => 'nl',
        'locale'   => 'nl_NL',
        'lcid'     => 1043,
        'codepage' => 1252,
    ],
    [
        'name'     => 'English - Australia',
        'language' => 'en',
        'locale'   => 'en_AU',
        'lcid'     => 3081,
        'codepage' => 1252,
    ],
    [
        'name'     => 'English - Belize',
        'language' => 'en',
        'locale'   => 'en_BZ',
        'lcid'     => 10249,
        'codepage' => 1252,
    ],
    [
        'name'     => 'English - Canada',
        'language' => 'en',
        'locale'   => 'en_CA',
        'lcid'     => 4105,
        'codepage' => 1252,
    ],
    [
        'name'     => 'English - Caribbean',
        'language' => 'en',
        'locale'   => 'en_CB',
        'lcid'     => 9225,
        'codepage' => 1252,
    ],
    [
        'name'     => 'English - Great Britain
        ',
        'language' => 'en',
        'locale'   => 'en_GB',
        'lcid'     => 2057,
        'codepage' => 1252,
    ],
    [
        'name'     => 'English - India',
        'language' => 'en',
        'locale'   => 'en_IN',
        'lcid'     => 16393,
    ],
    [
        'name'     => 'English - Ireland',
        'language' => 'en',
        'locale'   => 'en_IE',
        'lcid'     => 6153,
        'codepage' => 1252,
    ],
    [
        'name'     => 'English - Jamaica',
        'language' => 'en',
        'locale'   => 'en_JM',
        'lcid'     => 8201,
        'codepage' => 1252,
    ],
    [
        'name'     => 'English - New Zealand',
        'language' => 'en',
        'locale'   => 'en_NZ',
        'lcid'     => 5129,
        'codepage' => 1252,
    ],
    [
        'name'     => 'English - Phillippines',
        'language' => 'en',
        'locale'   => 'en_PH',
        'lcid'     => 13321,
        'codepage' => 1252,
    ],
    [
        'name'     => 'English - Southern Africa',
        'language' => 'en',
        'locale'   => 'en_ZA',
        'lcid'     => 7177,
        'codepage' => 1252,
    ],
    [
        'name'     => 'English - Trinidad',
        'language' => 'en',
        'locale'   => 'en_TT',
        'lcid'     => 11273,
        'codepage' => 1252,
    ],
    [
        'name'     => 'English - United States',
        'language' => 'en',
        'locale'   => 'en_US',
        'lcid'     => 1033,
        'codepage' => 1252,
    ],
    [
        'name'     => 'English - Zimbabwe',
        'language' => 'en',
        'lcid'     => 12297,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Estonian',
        'language' => 'et',
        'locale'   => 'et',
        'lcid'     => 1061,
        'codepage' => 1257,
    ],
    [
        'name'     => 'FYRO Macedonia',
        'language' => 'mk',
        'locale'   => 'mk',
        'lcid'     => 1071,
        'codepage' => 1251,
    ],
    [
        'name'     => 'Faroese',
        'language' => 'fo',
        'locale'   => 'fo',
        'lcid'     => 1080,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Farsi - Persian',
        'language' => 'fa',
        'locale'   => 'fa',
        'lcid'     => 1065,
        'codepage' => 1256,
    ],
    [
        'name'     => 'Finnish',
        'language' => 'fi',
        'locale'   => 'fi',
        'lcid'     => 1035,
        'codepage' => 1252,
    ],
    [
        'name'     => 'French - Belgium',
        'language' => 'fr',
        'locale'   => 'fr_BE',
        'lcid'     => 2060,
        'codepage' => 1252,
    ],
    [
        'name'     => 'French - Cameroon',
        'language' => 'fr',
        'lcid'     => 11276,
    ],
    [
        'name'     => 'French - Canada',
        'language' => 'fr',
        'locale'   => 'fr_CA',
        'lcid'     => 3084,
        'codepage' => 1252,
    ],
    [
        'name'     => 'French - Congo',
        'language' => 'fr',
        'lcid'     => 9228,
    ],
    [
        'name'     => "French - Cote d'Ivoire",
        'language' => 'fr',
        'lcid'     => 12300,
    ],
    [
        'name'     => 'French - France',
        'language' => 'fr',
        'locale'   => 'fr_FR',
        'lcid'     => 1036,
        'codepage' => 1252,
    ],
    [
        'name'     => 'French - Luxembourg',
        'language' => 'fr',
        'locale'   => 'fr_LU',
        'lcid'     => 5132,
        'codepage' => 1252,
    ],
    [
        'name'     => 'French - Mali',
        'language' => 'fr',
        'lcid'     => 13324,
    ],
    [
        'name'     => 'French - Monaco',
        'language' => 'fr',
        'lcid'     => 6156,
        'codepage' => 1252,
    ],
    [
        'name'     => 'French - Morocco',
        'language' => 'fr',
        'lcid'     => 14348,
    ],
    [
        'name'     => 'French - Senegal',
        'language' => 'fr',
        'lcid'     => 10252,
    ],
    [
        'name'     => 'French - Switzerland',
        'language' => 'fr',
        'locale'   => 'fr_CH',
        'lcid'     => 4108,
        'codepage' => 1252,
    ],
    [
        'name'     => 'French - West Indies',
        'language' => 'fr',
        'lcid'     => 7180,
    ],
    [
        'name'     => 'Gaelic - Ireland',
        'language' => 'gd',
        'locale'   => 'gd_IE',
        'lcid'     => 2108,
    ],
    [
        'name'     => 'Gaelic - Scotland',
        'language' => 'gd',
        'locale'   => 'gd',
        'lcid'     => 1084,
    ],
    [
        'name'     => 'Galician',
        'language' => 'gl',
        'lcid'     => 1110,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Georgian',
        'language' => 'ka',
        'lcid'     => 1079,
    ],
    [
        'name'     => 'German - Austria',
        'language' => 'de',
        'locale'   => 'de_AT',
        'lcid'     => 3079,
        'codepage' => 1252,
    ],
    [
        'name'     => 'German - Germany',
        'language' => 'de',
        'locale'   => 'de_DE',
        'lcid'     => 1031,
        'codepage' => 1252,
    ],
    [
        'name'     => 'German - Liechtenstein',
        'language' => 'de',
        'locale'   => 'de_LI',
        'lcid'     => 5127,
        'codepage' => 1252,
    ],
    [
        'name'     => 'German - Luxembourg',
        'language' => 'de',
        'locale'   => 'de_LU',
        'lcid'     => 4103,
        'codepage' => 1252,
    ],
    [
        'name'     => 'German - Switzerland',
        'language' => 'de',
        'locale'   => 'de_CH',
        'lcid'     => 2055,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Greek',
        'language' => 'el',
        'locale'   => 'el',
        'lcid'     => 1032,
        'codepage' => 1253,
    ],
    [
        'name'     => 'Guarani - Paraguay',
        'language' => 'gn',
        'locale'   => null, // INVALID ICU LOCALE 'gn',
        'lcid'     => 1140,
    ],
    [
        'name'     => 'Gujarati',
        'language' => 'gu',
        'locale'   => 'gu',
        'lcid'     => 1095,
    ],
    [
        'name'     => 'Hebrew',
        'language' => 'he',
        'locale'   => 'he',
        'lcid'     => 1037,
        'codepage' => 1255,
    ],
    [
        'name'     => 'Hindi',
        'language' => 'hi',
        'locale'   => 'hi',
        'lcid'     => 1081,
    ],
    [
        'name'     => 'Hungarian',
        'language' => 'hu',
        'locale'   => 'hu',
        'lcid'     => 1038,
        'codepage' => 1250,
    ],
    [
        'name'     => 'Icelandic',
        'language' => 'is',
        'locale'   => 'is',
        'lcid'     => 1039,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Indonesian',
        'language' => 'id',
        'locale'   => 'id',
        'lcid'     => 1057,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Italian - Italy',
        'language' => 'it',
        'locale'   => 'it_IT',
        'lcid'     => 1040,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Italian - Switzerland',
        'language' => 'it',
        'locale'   => 'it_CH',
        'lcid'     => 2064,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Japanese',
        'language' => 'ja',
        'locale'   => 'ja',
        'lcid'     => 1041,
    ],
    [
        'name'     => 'Kannada',
        'language' => 'kn',
        'locale'   => 'kn',
        'lcid'     => 1099,
    ],
    [
        'name'     => 'Kashmiri',
        'language' => 'ks',
        'locale'   => 'ks',
        'lcid'     => 1120,
    ],
    [
        'name'     => 'Kazakh',
        'language' => 'kk',
        'locale'   => 'kk',
        'lcid'     => 1087,
        'codepage' => 1251,
    ],
    [
        'name'     => 'Khmer',
        'language' => 'km',
        'locale'   => 'km',
        'lcid'     => 1107,
    ],
    [
        'name'     => 'Korean',
        'language' => 'ko',
        'locale'   => 'ko',
        'lcid'     => 1042,
    ],
    [
        'name'     => 'Lao',
        'language' => 'lo',
        'locale'   => 'lo',
        'lcid'     => 1108,
    ],
    [
        'name'     => 'Latin',
        'language' => 'la',
        'locale'   => 'la',
        'lcid'     => 1142,
    ],
    [
        'name'     => 'Latvian',
        'language' => 'lv',
        'locale'   => 'lv',
        'lcid'     => 1062,
        'codepage' => 1257,
    ],
    [
        'name'     => 'Lithuanian',
        'language' => 'lt',
        'locale'   => 'lt',
        'lcid'     => 1063,
        'codepage' => 1257,
    ],
    [
        'name'     => 'Malay - Brunei',
        'language' => 'ms',
        'locale'   => 'ms_BN',
        'lcid'     => 2110,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Malay - Malaysia',
        'language' => 'ms',
        'locale'   => 'ms_MY',
        'lcid'     => 1086,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Malayalam',
        'language' => 'ml',
        'locale'   => 'ml',
        'lcid'     => 1100,
    ],
    [
        'name'     => 'Maltese',
        'language' => 'mt',
        'locale'   => 'mt',
        'lcid'     => 1082,
    ],
    [
        'name'     => 'Maori',
        'language' => 'mi',
        'locale'   => 'mi',
        'lcid'     => 1153,
    ],
    [
        'name'     => 'Marathi',
        'language' => 'mr',
        'locale'   => 'mr',
        'lcid'     => 1102,
    ],
    [
        'name'     => 'Mongolian',
        'language' => 'mn',
        'locale'   => 'mn',
        'lcid'     => 1104,
        'codepage' => 1251,
    ],
    [
        'name'     => 'Mongolian',
        'language' => 'mn',
        'locale'   => 'mn',
        'lcid'     => 2128,
    ],
    [
        'name'     => 'Nepali',
        'language' => 'ne',
        'locale'   => 'ne',
        'lcid'     => 1121,
    ],
    [
        'name'     => 'Norwegian - Bokml',
        'language' => 'nb',
        'locale'   => 'no_NO',
        'lcid'     => 1044,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Norwegian - Nynorsk',
        'language' => 'nn',
        'locale'   => 'no_NO',
        'lcid'     => 2068,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Oriya',
        'language' => 'or',
        'locale'   => 'or',
        'lcid'     => 1096,
    ],
    [
        'name'     => 'Polish',
        'language' => 'pl',
        'locale'   => 'pl',
        'lcid'     => 1045,
        'codepage' => 1250,
    ],
    [
        'name'     => 'Portuguese - Brazil',
        'language' => 'pt',
        'locale'   => 'pt_BR',
        'lcid'     => 1046,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Portuguese - Portugal',
        'language' => 'pt',
        'locale'   => 'pt_PT',
        'lcid'     => 2070,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Punjabi',
        'language' => 'pa',
        'locale'   => 'pa',
        'lcid'     => 1094,
    ],
    [
        'name'     => 'Raeto-Romance',
        'language' => 'rm',
        'locale'   => 'rm',
        'lcid'     => 1047,
    ],
    [
        'name'     => 'Romanian - Moldova',
        'language' => 'ro',
        'locale'   => 'ro_MO',
        'lcid'     => 2072,
    ],
    [
        'name'     => 'Romanian - Romania',
        'language' => 'ro',
        'locale'   => 'ro_RO',
        'lcid'     => 1048,
        'codepage' => 1250,
    ],
    [
        'name'     => 'Russian',
        'language' => 'ru',
        'locale'   => 'ru_RU',
        'lcid'     => 1049,
        'codepage' => 1251,
    ],
    [
        'name'     => 'Russian - Moldova',
        'language' => 'ru',
        'locale'   => 'ru_MO',
        'lcid'     => 2073,
    ],
    [
        'name'     => 'Sanskrit',
        'language' => 'sa',
        'locale'   => 'sa',
        'lcid'     => 1103,
    ],
    [
        'name'     => 'Serbian - Cyrillic',
        'language' => 'sr',
        'locale'   => 'sr_SP',
        'lcid'     => 3098,
        'codepage' => 1251,
    ],
    [
        'name'     => 'Serbian - Latin',
        'language' => 'sr',
        'locale'   => 'sr_SP',
        'lcid'     => 2074,
        'codepage' => 1250,
    ],
    [
        'name'     => 'Setsuana',
        'language' => 'tn',
        'locale'   => 'tn',
        'lcid'     => 1074,
    ],
    [
        'name'     => 'Sindhi',
        'language' => 'sd',
        'locale'   => 'sd',
        'lcid'     => 1113,
    ],
    [
        'name'     => 'Sinhala Sinhalese',
        'language' => 'si',
        'locale'   => 'si',
        'lcid'     => 1115,
    ],
    [
        'name'     => 'Slovak',
        'language' => 'sk',
        'locale'   => 'sk',
        'lcid'     => 1051,
        'codepage' => 1250,
    ],
    [
        'name'     => 'Slovenian',
        'language' => 'sl',
        'locale'   => 'sl',
        'lcid'     => 1060,
        'codepage' => 1250,
    ],
    [
        'name'     => 'Somali',
        'language' => 'so',
        'locale'   => 'so',
        'lcid'     => 1143,
    ],
    [
        'name'     => 'Sorbian',
        'language' => 'sb',
        'locale'   => 'sb',
        'lcid'     => 1070,
    ],
    [
        'name'     => 'Spanish - Argentina',
        'language' => 'es',
        'locale'   => 'es_AR',
        'lcid'     => 11274,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Spanish - Bolivia',
        'language' => 'es',
        'locale'   => 'es_BO',
        'lcid'     => 16394,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Spanish - Chile',
        'language' => 'es',
        'locale'   => 'es_CL',
        'lcid'     => 13322,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Spanish - Colombia',
        'language' => 'es',
        'locale'   => 'es_CO',
        'lcid'     => 9226,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Spanish - Costa Rica',
        'language' => 'es',
        'locale'   => 'es_CR',
        'lcid'     => 5130,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Spanish - Dominican Republic',
        'language' => 'es',
        'locale'   => 'es_DO',
        'lcid'     => 7178,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Spanish - Ecuador',
        'language' => 'es',
        'locale'   => 'es_EC',
        'lcid'     => 12298,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Spanish - El Salvador',
        'language' => 'es',
        'locale'   => 'es_SV',
        'lcid'     => 17418,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Spanish - Guatemala',
        'language' => 'es',
        'locale'   => 'es_GT',
        'lcid'     => 4106,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Spanish - Honduras',
        'language' => 'es',
        'locale'   => 'es_HN',
        'lcid'     => 18442,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Spanish - Mexico',
        'language' => 'es',
        'locale'   => 'es_MX',
        'lcid'     => 2058,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Spanish - Nicaragua',
        'language' => 'es',
        'locale'   => 'es_NI',
        'lcid'     => 19466,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Spanish - Panama',
        'language' => 'es',
        'locale'   => 'es_PA',
        'lcid'     => 6154,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Spanish - Paraguay',
        'language' => 'es',
        'locale'   => 'es_PY',
        'lcid'     => 15370,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Spanish - Peru',
        'language' => 'es',
        'locale'   => 'es_PE',
        'lcid'     => 10250,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Spanish - Puerto Rico',
        'language' => 'es',
        'locale'   => 'es_PR',
        'lcid'     => 20490,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Spanish - Spain (Traditional)',
        'language' => 'es',
        'locale'   => 'es_ES',
        'lcid'     => 1034,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Spanish - Uruguay',
        'language' => 'es',
        'locale'   => 'es_UY',
        'lcid'     => 14346,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Spanish - Venezuela',
        'language' => 'es',
        'locale'   => 'es_VE',
        'lcid'     => 8202,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Swahili',
        'language' => 'sw',
        'locale'   => 'sw',
        'lcid'     => 1089,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Swedish - Finland',
        'language' => 'sv',
        'locale'   => 'sv_FI',
        'lcid'     => 2077,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Swedish - Sweden',
        'language' => 'sv',
        'locale'   => 'sv_SE',
        'lcid'     => 1053,
        'codepage' => 1252,
    ],
    [
        'name'     => 'Tajik',
        'language' => 'tg',
        'locale'   => 'tg',
        'lcid'     => 1064,
    ],
    [
        'name'     => 'Tamil',
        'language' => 'ta',
        'locale'   => 'ta',
        'lcid'     => 1097,
    ],
    [
        'name'     => 'Tatar',
        'language' => 'tt',
        'locale'   => 'tt',
        'lcid'     => 1092,
        'codepage' => 1251,
    ],
    [
        'name'     => 'Telugu',
        'language' => 'te',
        'locale'   => 'te',
        'lcid'     => 1098,
    ],
    [
        'name'     => 'Thai',
        'language' => 'th',
        'locale'   => 'th',
        'lcid'     => 1054,
    ],
    [
        'name'     => 'Tibetan',
        'language' => 'bo',
        'locale'   => 'bo',
        'lcid'     => 1105,
    ],
    [
        'name'     => 'Tsonga',
        'language' => 'ts',
        'locale'   => 'ts',
        'lcid'     => 1073,
    ],
    [
        'name'     => 'Turkish',
        'language' => 'tr',
        'locale'   => 'tr',
        'lcid'     => 1055,
        'codepage' => 1254,
    ],
    [
        'name'     => 'Turkmen',
        'language' => 'tk',
        'locale'   => 'tk',
        'lcid'     => 1090,
    ],
    [
        'name'     => 'Ukrainian',
        'language' => 'uk',
        'locale'   => 'uk',
        'lcid'     => 1058,
        'codepage' => 1251,
    ],
    [
        'name'     => 'Urdu',
        'language' => 'ur',
        'locale'   => 'ur',
        'lcid'     => 1056,
        'codepage' => 1256,
    ],
    [
        'name'     => 'Uzbek - Cyrillic',
        'language' => 'uz',
        'locale'   => 'uz_UZ',
        'lcid'     => 2115,
        'codepage' => 1251,
    ],
    [
        'name'     => 'Uzbek - Latin',
        'language' => 'uz',
        'locale'   => 'uz_UZ',
        'lcid'     => 1091,
        'codepage' => 1254,
    ],
    [
        'name'     => 'Vietnamese',
        'language' => 'vi',
        'locale'   => 'vi',
        'lcid'     => 1066,
        'codepage' => 1258,
    ],
    [
        'name'     => 'Welsh',
        'language' => 'cy',
        'locale'   => 'cy',
        'lcid'     => 1106,
    ],
    [
        'name'     => 'Xhosa',
        'language' => 'xh',
        'locale'   => 'xh',
        'lcid'     => 1076,
    ],
    [
        'name'     => 'Yiddish',
        'language' => 'yi',
        'locale'   => 'yi',
        'lcid'     => 1085,
    ],
    [
        'name'     => 'Zulu',
        'language' => 'zu',
        'locale'   => 'zu',
        'lcid'     => 1077,
    ],
    [
        'name'     => 'Syriac - Syria',
        'language' => 'syc',
        'locale'   => 'syc_SY',
        'lcid'     => 1114,
    ],
    [
        'name'     => 'Divehi - Maldives',
        'language' => 'dv',
        'locale'   => 'dv_MV',
        'lcid'     => 1125,
    ],
    [
        'name'     => 'Konkani - India',
        'language' => 'kok',
        'locale'   => 'kok_IN',
        'lcid'     => 1111,
    ],
    [
        'name'     => 'Sanskrit - India',
        'language' => 'sa',
        'locale'   => 'sa_IN',
        'lcid'     => 1103,
    ],
];
